### PR TITLE
6.2.x

### PR DESCRIPTION
**Pull request by duccom**

### CODE REVIEW

**Comment by KallelOmar** [comment]
Hello I have just cloned the branch 6.2.x in order to get the source of the calendar portlet so I can customize it. After I deployed this portlet I get this exception com.liferay.portal.kernel.bean.BeanLocatorException: org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'com.liferay.calendar.service.persistence.CalendarBookingPersistence' is defined
How I can solve it?

**Comment by zafarale** [comment]
Hi Chaps, Just wondering if i can use this plugin with external Solr 5.3

**Comment by adnangul** [comment]
@zafarale  which plugin you referring?

**Comment by zafarale** [comment]
I am looking to integrate Solr 5.3 via Liferay6.2 Solr Plugin

**Comment by adnangul** [comment]
Zafarale
The schema provided with the plugin will not work out of the box; also the
recommended configuration will not for cluster (master slaves).

However, you can quickly figure out what need to be modified in schema to
make it running. Do cluster your solr instance/cloud and point to that url
(http url off cource ) in plugin

Adnan

On Mon, Dec 21, 2015 at 10:51 AM, zafarale <notifications@github.com> wrote:

> I am looking to integrate Solr 5.3 via Liferay6.2 Solr Plugin
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/liferay/liferay-plugins/pull/107#issuecomment-166356976>
> .
>



-- 
Regards,
*Adnan Yaqoob*

**Pull request closed without merging**
