### PR TITLE
LPS-43807 Google Login hook

### PR DESCRIPTION
**Pull request by fbudassi**
Migrated from Google OpenID 2.0 (deprecated since mid 2014) to Google+ Sign-In (https://developers.google.com/+/api/auth-migration). This
includes updating dependencies and the Scopes used.

Approval Prompt set from "force" to "auto" to avoid showing the confirmation dialog each time
the user logs in with Google+.

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
Hey @fbudassi 

Thanks a lot for helping find this and send us the code to update it. Before we can merge this in our official repo you need to accept Liferay Contributor's Agreement because otherwise we can't merge your code.

I have created a new LPS to reflect this: https://issues.liferay.com/browse/LPS-54523. You need to click there in Contribute Solution, Accept the Liferay Contributor's Agreement and specify this pull request in the Git Pull request field.

Once we have that ready I'll go ahead and merge the pull.

Thanks,
Sergio

**Comment by fbudassi** [comment]
Hi @sergiogonzalez,

Thanks for the attention to this pull request. It would also be helpful to have these modifications in the master branch (currently Liferay 7). However, I don't have a test rig already configured and I have a lack of knowledge about it (never tested in the past... only when it finally comes out as a GA).
The thing is, would it be possible for somebody to merge the changes in the master branch as well? I believe it'll be useful for more than a couple of people, according to what I've seen on StackOverflow and some other forums.

Btw, I have already accepted the Contribute Solution agreement and done what you've 

Thanks in advance,
Federico.

**Comment by sergiogonzalez** [comment]
Sure!! I'll deal with the master branch :)

Sergio

**Comment by sergiogonzalez** [comment]
Done. I have sent the pull to Brian for the final review:

https://github.com/brianchandotcom/liferay-plugins/pull/4448
https://github.com/brianchandotcom/liferay-plugins/pull/4447

Thanks a lot for the update.
Sergio

**Comment by obsolete0815** [comment]
Vielen Dank für Ihre E-Mail. Ich bin bis einschließlich 10.04.2015 nicht im Büro. Ihre E-Mails werden während dieser Zeit nicht weitergeleitet. Bitte wenden Sie sich in dringenden Fällen an Herrn Anhal Osman (Tel. 0531/40209653 oder anhal.osman@codefrog.de). Am 13.04.2015 bin ich wieder für Sie da!

Beste Grüße und schöne Osterfeiertage

Birgit Prokopp

**Pull request closed without merging**
